version: '3.1'

services:
  web:
    build: ./
    command: ./docker-entrypoint.sh
    env_file:
      - ./config/web/web-variables.env
    volumes:
      - ./:/web
    ports:
      - "443:443"
      - "80:80"